language: bash

before_script:
  - export RELEASE_FILE=webyneter-zsh-goodies.zsh
script:
    # - bash -c "find . -type f -name '*.zsh' -exec cat {} \; > 'webyneter-zsh-goodies.zsh'"
    - find . -type f -name "*.zsh" -exec cat {} \; > RELEASE_FILE

before_deploy:
  - echo "Deploying $RELEASE_FILE..."
deploy:
  provider: releases
  skip_cleanup: true
  # api_key: "GITHUB OAUTH TOKEN"
  file: $RELEASE_FILE
  on_success:
    