language: bash

before_script:
  - echo "Combining all zsh files into $RELEASE_FILE..."
script:
    - find . -type f -name "*.zsh" -exec cat {} \; > $RELEASE_FILE

before_deploy:
  - echo "Deploying $RELEASE_FILE..."
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $API_KEY
  file: $RELEASE_FILE
  on_success:
    - echo "$RELEASE_FILE deployed!"
